postgresql_settings: &postgresql_settings
  adapter: postgresql
  encoding: unicode
  pool: 50
  username: <%= Rails.application.credentials[:POSTGRES_USER] %>
  password: <%= Rails.application.credentials[:POSTGRES_PASSWORD] %>
  host: <%= Rails.application.credentials[:POSTGRES_HOST] %>
  port: 5432

development:
  <<: *postgresql_settings
  database: <%= Rails.application.credentials[:POSTGRES_DB] %>		
production:
  <<: *postgresql_settings
  database: <%= Rails.application.credentials[:POSTGRES_PRODUCTION] %>
  