mysql_settings: &mysql_settings
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: your-mysql-user-here
  password: your-mysql-password-here
  host: your-mysql-IPv4-address-here
  database: your-mysql-database-here

postgresql_settings: &postgresql_settings
  adapter: postgresql
  encoding: unicode
  pool: 50
  username: <%= Rails.application.credentials[:POSTGRES_USER] %>
  password: <%= Rails.application.credentials[:POSTGRES_PASSWORD] %>
  host: <%= Rails.application.credentials[:POSTGRES_HOST] %>
  port: 5432
  database: <%= Rails.application.credentials[:POSTGRES_DB] %>

development:
  <<: *postgresql_settings
  database: <%= Rails.application.credentials[:POSTGRES_DB] %>		
production:
  <<: *postgresql_settings
  database: <%= Rails.application.credentials[:POSTGRES_PRODUCTION] %>
  