postgresql_settings: &postgresql_settings
  adapter: postgresql
  encoding: unicode
  pool: 50
  username: <%= Rails.application.credentials[:POSTGRES_USER] %>
  password: <%= Rails.application.credentials[:POSTGRES_PASSWORD] %>
  host: 34.68.137.106
  port: 5432

development:
  <<: *postgresql_settings
  database: <%= Rails.application.credentials[:POSTGRES_DB] %>		
production:
  <<: *postgresql_settings
  database: <%= Rails.application.credentials[:POSTGRES_PRODUCTION] %>

test:
  adapter: postgresql
  encoding: unicode
  pool: 50
  username: root
  password:
  host: localhost
  port: 5432
  database: api_test
  
