postgresql_settings: &postgresql_settings
  adapter: postgresql
  encoding: unicode
  pool: 50
  username: postgres
  password: d1ZrAsDaNGG5
  host: 35.222.137.96
  port: 5432

development:
  <<: *postgresql_settings
  database: troca_db_development
production:
  <<: *postgresql_settings
  database: troca_db_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 50
  username: root
  password:
  host: localhost
  port: 5432
  database: troca_db_test
  
